# -*- coding: utf-8 -*-
"""lab 2 task 1.pngz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FL3ubCG-ETTsTWjftomhLZbBhSRfkQ4s
"""



"""First, you'll need to mount your Google Drive to access the file."""

from google.colab import drive
drive.mount('/content/drive')

"""Now, here is the function to analyze your CSV file. Remember to update the `file_path` and `column_name` variables in the example usage with the correct values for your file."""

import pandas as pd

def analyze_csv_from_drive(file_path, column_name):
  """
  Reads a CSV file from Google Drive, calculates descriptive statistics
  (mean, min, max) for a specified numeric column, and prints the results.

  Args:
    file_path (str): The full path to the CSV file in Google Drive
                     (e.g., '/content/drive/My Drive/students.csv').
    column_name (str): The name of the numeric column to analyze.
  """
  try:
    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv(file_path)
    print(f"Successfully read '{file_path}'")
    print("-" * 30) # Separator for clarity

    # Check if the specified column exists in the DataFrame
    if column_name not in df.columns:
      print(f"Error: Column '{column_name}' not found in the CSV file.")
      return

    # Check if the column is numeric
    if not pd.api.types.is_numeric_dtype(df[column_name]):
        print(f"Error: Column '{column_name}' is not numeric.")
        return

    # Calculate descriptive statistics
    mean_value = df[column_name].mean()
    min_value = df[column_name].min()
    max_value = df[column_name].max()

    # Print the results
    print(f"Analysis for column: '{column_name}'")
    print(f"Mean: {mean_value:.2f}")
    print(f"Minimum: {min_value:.2f}")
    print(f"Maximum: {max_value:.2f}")

  except FileNotFoundError:
    print(f"Error: File not found at '{file_path}'. Please check the path.")
  except Exception as e:
    print(f"An error occurred: {e}")

# Example usage:
# Replace 'My Drive/students.csv' with the actual path to your file
# Replace 'Score' with the actual name of the numeric column
file_path = '/content/drive/My Drive/students.csv'
column_name = 'Score'

analyze_csv_from_drive(file_path, column_name)